pdf_names = [
        "none",
        "Lei Day: Celebrating Hawaii's culture of aloha",
        "Gear Up for a paintball adventure",
        "The Dark masterpieces of bruegel and picasso",
        "Paintings in history: guernica by pablo picasso",
        "none",
        "Fully furnished studio in xinyi district available now",
        "A smooth start for new roommates",
        "The sharing economy: a way to access what you need",
        "none",
        "A journey through time: the pyramids of latin america",
        "none",
        "taipei metro encourages two-sided escalator use",
        "none",
        "the world of sausages: a glbal culinary delight",
        "none",
        "South Sudan's blind league inspieres hope and unity",
        "none",
        "Nazar boncugu: yowr talisman for good luck charm",
        "none",
        "Lady gaga: abracadabra!",
        "none",
        "Gout: the disease of kings",
        "magical wishes meet harsh reality in the seven wish",
        "none",
]
